spring:
  application:
    name: client-consent
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app_consent?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: asdasd
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always