spring:
  spring:
    resources:
      static-locations=classpath:/static/
    main:
      allow-bean-definition-overriding: true
    application:
      name: client-consent
    datasource:
      url: jdbc:mariadb://localhost:3306/app_consent?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: asdasd
      driver-class-name: org.mariadb.jdbc.Driver
    flyway:
      locations: classpath:db/migration
    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: true
    profiles:
      active: local