spring:
  spring:
    resources:
      static-locations=classpath:/static/
    main:
      allow-bean-definition-overriding: true
    application:
      name: client-consent

    profiles:
      active: local