spring:
  application:
    name: client-consent
  datasource:
    url: jdbc:mariadb://localhost:3306/app_consent?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: asdasd
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    show-sql: true



server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace