spring:
  spring:
    resources:
      static-locations=classpath:/static/
    main:
      allow-bean-definition-overriding: true
    application:
      name: client-consent

    profiles:
      active: local

email:
  verfication-email: qv.cas.nl@digicert.com

server:
  port: 8092
  servlet:
    context-path: /consent/
  error:
    include-binding-errors: always
    include-message: always
