products:
  - name: "eu_qualified_manual"
    description: "eu qualified manual product"
  - name: "eu_qualified_auto"
    description: "eu manual product"
  - name: "aatl_auto"
    description: "aatl auto product"
  - name: "aatl_manual"
    description: "aatl manual product"